#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Starting pre-commit hook"

bun run lint
if [ $? -ne 0 ]; then
  echo "Linting failed"
  exit 1
fi

bun run format
if [ $? -ne 0 ]; then
  echo "Formatting failed"
  exit 1
fi

echo "Pre-commit hook succeeded"
