name: CI

# CIワークフローの名前を定義します

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# mainブランチへのプッシュまたはプルリクエストでワークフローをトリガーします

jobs:
  lint:
    runs-on: ubuntu-latest
    # lintジョブを定義し、最新のUbuntu環境で実行します

    steps:
      - uses: actions/checkout@v3
      # リポジトリのコードをチェックアウトします

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.30
      # Bunランタイムをセットアップします（バージョン1.1.30を指定）

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      # Bunの依存関係とnode_modulesを一緒にキャッシュします
      # キャッシュキーはOSとbun.lockbファイルのハッシュに基づいています

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile
      # キャッシュヒットがない場合のみ依存関係をインストールします

      - name: Create Biome configuration
        run: |
          cat << 'EOF' > biome.json
          {
            "$schema": "https://biomejs.dev/schemas/1.8.0/schema.json",
            "organizeImports": {
              "enabled": true,
              "ignore": ["**/dist", "**/node_modules/", "**/*.d.ts"]
            },
            "formatter": {
              "enabled": true,
              "formatWithErrors": true,
              "indentStyle": "space",
              "indentWidth": 2,
              "lineEnding": "lf",
              "lineWidth": 80,
              "attributePosition": "auto",
              "ignore": [
                "**/node_modules/**",
                "**/dist/**",
                "**/dist-ssr/**",
                "**/build/**",
                "**/coverage/**",
                "**/.git/**",
                "**/.vscode/**",
                "**/.idea/**",
                "**/.DS_Store",
                "**/yarn.lock",
                "**/package-lock.json",
                "**/yarn-error.log",
                "**/storybook-static/**",
                "**/*.d.ts",
                "**/*.local",
                "**/*.log",
                "**/tailwind.config.js",
                "**/postcss.config.cjs",
                "**/.env"
              ]
            },
            "linter": {
              "enabled": true,
              "rules": {
                "recommended": true
              },
              "ignore": [
                "**/dist/**",
                "**/dist-ssr/**",
                "**/node_modules/**",
                "**/tailwind.config.js",
                "**/postcss.config.cjs",
                "**/storybook-static/**",
                "**/*.d.ts",
                "**/*.local",
                "**/*.log",
                "**/.env",
                "**/.vscode/settings.json"
              ]
            },
            "javascript": {
              "formatter": {
                "quoteStyle": "single"
              }
            },
            "json": {
              "parser": {
                "allowComments": true
              },
              "formatter": {
                "enabled": false
              }
            }
          }
          EOF
      # Biome（コードフォーマッタとリンター）の設定ファイルを作成します

      - name: Run Biome Lint
        run: bunx @biomejs/biome lint --config-path=biome.json .
      # Biomeを使用してリントを実行します

      - name: Cleanup before caching
        run: |
          rm -rf node_modules/.cache
          rm -rf node_modules/.vite
      # キャッシュ前に不要なファイルを削除します
      # 注：npm prune --productionは削除しました。Bunプロジェクトでは不要な場合があります

      - name: Update cache if needed
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/bun.lockb') }}
      # 依存関係に変更があった場合のみ、キャッシュを更新します
