# GitHub Packagesへのパッケージ公開ワークフロー
name: CI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  pre-publish-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pre-publish check executed"

  publish:
    needs: pre-publish-check
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@boxpistols'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Verify version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Package version: $PACKAGE_VERSION"
          echo "Release version: $RELEASE_VERSION"
          if [ "$PACKAGE_VERSION" != "$RELEASE_VERSION" ]; then
            echo "::error::パッケージバージョン($PACKAGE_VERSION)とタグバージョン($RELEASE_VERSION)が異なります"
            exit 1
          fi

      # ライブラリのビルド
      - name: Build library
        run: pnpm run build:lib

      - name: Build summary
        run: |
          echo "## ビルド結果" >> $GITHUB_STEP_SUMMARY
          echo "- パッケージバージョン: $(node -p "require('./package.json').version")" >> $GITHUB_STEP_SUMMARY
          echo "- ビルドファイル:" >> $GITHUB_STEP_SUMMARY
          ls -la dist | grep -v "^d" | awk '{print "  - " $9 " (" $5 " bytes)"}' >> $GITHUB_STEP_SUMMARY

      # NPM公開
      - name: Publish package
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish success
        if: success()
        run: |
          echo "## パブリッシュ成功 :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "- パッケージ: $(node -p "require('./package.json').name")" >> $GITHUB_STEP_SUMMARY
          echo "- バージョン: $(node -p "require('./package.json').version")" >> $GITHUB_STEP_SUMMARY
          echo "- 公開日時: $(date)" >> $GITHUB_STEP_SUMMARY
