name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create Biome configuration
        run: |
          cat << EOF > biome.json
          {
            "$schema": "https://biomejs.dev/schemas/1.8.0/schema.json",
            "organizeImports": {
              "enabled": true,
              "ignore": ["**/dist", "**/node_modules/", "**/*.d.ts"]
            },
            "formatter": {
              "enabled": true,
              "formatWithErrors": true,
              "indentStyle": "space",
              "indentWidth": 2,
              "lineEnding": "lf",
              "lineWidth": 80,
              "attributePosition": "auto",
              "ignore": [
                "**/node_modules/**",
                "**/dist/**",
                "**/dist-ssr/**",
                "**/build/**",
                "**/coverage/**",
                "**/.git/**",
                "**/.vscode/**",
                "**/.idea/**",
                "**/.DS_Store",
                "**/yarn.lock",
                "**/package-lock.json",
                "**/yarn-error.log",
                "**/storybook-static/**",
                "**/*.d.ts",
                "**/*.local",
                "**/*.log",
                "**/tailwind.config.js",
                "**/postcss.config.cjs",
                "**/.env"
              ]
            },
            "linter": {
              "enabled": true,
              "rules": {
                "recommended": true
              },
              "ignore": [
                "**/dist/**",
                "**/dist-ssr/**",
                "**/node_modules/**",
                "**/tailwind.config.js",
                "**/postcss.config.cjs",
                "**/storybook-static/**",
                "**/*.d.ts",
                "**/*.local",
                "**/*.log",
                "**/.env"
              ]
            }
          }
          EOF

      - name: Run Biome Lint
        run: bunx @biomejs/biome lint --config-path=biome.json .
