name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
          cache: 'pnpm'

      # 最適化されたキャッシュ設定
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/node_modules
            !**/node_modules/.cache
            !**/node_modules/.vite
            !**/node_modules/.rollup.cache
            !**/*.log
          key: ${{ runner.os }}-deps-${{ hashFiles('pnpm-lock.yaml') }}-v1
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Lint and Format
        run: pnpm run fix

      # クリーンアップとビルド
      - name: Build
        run: |
          # キャッシュのクリーンアップ
          find . -type d -name ".cache" -exec rm -rf {} +
          find . -type d -name ".vite" -exec rm -rf {} +
          # ビルド実行
          pnpm run build
          pnpm run build:sb
