name: 手動パッケージ公開

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'パッケージのバージョン（例: 0.0.11）'
        required: true
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # OIDC認証のために追加

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: pnpmセットアップ
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Node.jsセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@boxpistols'
          always-auth: true # 常に認証を要求

      - name: バージョン確認
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "現在のバージョン: $CURRENT_VERSION"
          echo "公開するバージョン: ${{ github.event.inputs.version }}"

          if [ "$CURRENT_VERSION" != "${{ github.event.inputs.version }}" ]; then
            echo "バージョンが一致しません。package.jsonを更新します。"
            sed -i "s/\"version\": \"$CURRENT_VERSION\"/\"version\": \"${{ github.event.inputs.version }}\"/" package.json
          fi

      - name: 依存パッケージのインストール
        run: pnpm install --no-frozen-lockfile

      - name: ライブラリのビルド
        run: pnpm run build:lib

      - name: 認証情報の確認
        run: |
          echo "レジストリURL: $(npm config get registry)"
          echo "スコープ: @boxpistols"
          echo "NODE_AUTH_TOKEN環境変数が設定されているか: ${{ env.NODE_AUTH_TOKEN != '' }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: パッケージの公開
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "@boxpistols:registry=https://npm.pkg.github.com" >> .npmrc
          npm publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 公開サマリー
        if: success()
        run: |
          echo "## パブリッシュ成功 :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "- パッケージ: $(node -p 'require("./package.json").name') v$(node -p 'require("./package.json").version')" >> $GITHUB_STEP_SUMMARY
          echo "- 公開日時: $(date)" >> $GITHUB_STEP_SUMMARY
