# mainブランチへのプッシュ時にトリガーされ、GitHub Packagesにパッケージを公開します
# 条件として、package.jsonが変更された場合にのみ実行されます
name: Publish Package
"on":
    push:
        branches:
            - main
        paths:
            - package.json # package.jsonの変更時に実行
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.13.1
                  registry-url: https://npm.pkg.github.com
                  scope: "@boxpistols"
            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile
            - name: Build library
              run: pnpm run build:lib
            - name: Publish package
              run: pnpm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish summary
              if: success()
              run: |
                  echo "## パブリッシュ成功 :rocket:" >> $GITHUB_STEP_SUMMARY
                  echo "- パッケージ: $(node -p 'require("./package.json").name') v$(node -p 'require("./package.json").version')" >> $GITHUB_STEP_SUMMARY
                  echo "- 公開日時: $(date)" >> $GITHUB_STEP_SUMMARY
